### ISSUE TITLE
feature/mypage

### ISSUE THREAD

**Issue by junwon1997** [Pureum-umc-app/Pureum-BE#48]
## 📌  Feature Description
마이페이지
## 📝  To-do
- [x] 프로필 반환 API 
- [ ] 나의 배지 리스트 반환 API 
- [x] 나의 문장 리스트 반환 API 
- [x] 문장 수정 API 
- [x] 문장 삭제 API 
- [ ] 나의 도전 리스트 반환 API 
- [x] 프로필 수정 API
