### ISSUE TITLE
feature/use

### ISSUE THREAD

**Issue by junwon1997** [Pureum-umc-app/Pureum-BE#6]
## 📌  Feature Description
Make api for use entity
## 📝  To-do
- [x] 일일 사용 시간, 휴대폰 켠 횟수 저장 API
- [x] 오늘의 목표 사용 시간 반환 API
- [x] 과거 사용 기록 반환 API
- [x] 목표 사용 시간 설정 API
- [x] 나의 학년 카테고리 반환 API
