### ISSUE TITLE
feature/battle

### ISSUE THREAD

**Issue by joeun-01** [Pureum-umc-app/Pureum-BE#61]
## 📌  Feature Description
대결하기

## 📝  To-do
- [x] 대결 키워드 3개 반환 API
- [x] 대결 상대 리스트 반환 API
- [ ] 대결 신청하기 API
- [x] 프로필 사진 반환 API
- [x] 대결 수락하기 API
- [x] 대결 거절하기 API
- [x] 대결 취소하기 API
- [ ] 대결 받은 사람 대결 문장 작성 API
- [x] 대기 중인 대결 리스트 반환 API
- [x] 진행 중인 대결 리스트 반환 API
- [x] 종료된 대결 리스트 반환 API
- [ ] 대결 정보 반환 (진행 중) API
- [ ] 대결 정보 반환 (종료) API
- [x] 나의 진행 중인 대결 리스트 반환 API
- [x] 나의 종료된 대결 리스트 반환 API
- [x] 문장 좋아요 하기 API
- [x] 문장 좋아요 취소하기 API
